apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal-ai-assistant
  labels:
    app: personal-ai-assistant
spec:
  replicas: 1
  selector:
    matchLabels:
      app: personal-ai-assistant
  template:
    metadata:
      labels:
        app: personal-ai-assistant
    spec:
      containers:
        # Backend container
        - name: backend
          image: sumba729/personal-ai-assistant:latest
          ports:
            - containerPort: 5000
          env:
            - name: OPENAI_API_KEY
              valueFrom:
                secretKeyRef:
                  name: openai-secret
                  key: OPENAI_API_KEY
            - name: OPENAI_MODEL
              value: "gpt-4o-mini"
        # Frontend container
        - name: frontend
          image: sumba729/personal-ai-frontend:latest  # React app built and containerized
          ports:
            - containerPort: 80
