apiVersion: v1
kind: Service
metadata:
  name: personal-ai-assistant
  labels:
    app: personal-ai-assistant
spec:
  selector:
    app: personal-ai-assistant
  type: LoadBalancer
  ports:
    - name: frontend
      port: 3000
      targetPort: 3000
    - name: backend
      port: 5000
      targetPort: 5000
