apiVersion: v1
kind: Service
metadata:
  name: personal-ai-assistant
spec:
  selector:
    app: personal-ai-assistant
  type: NodePort
  ports:
    - name: frontend
      port: 80
      targetPort: 80
      nodePort: 30080
    - name: backend
      port: 5000
      targetPort: 5000
      nodePort: 30500
